---
- name: "End the play for hosts that do not run CentOS or RHEL"
  meta: end_host
  when:
  - ansible_distribution != 'CentOS' and ansible_distribution != 'RedHat' 
  notify: "Stop Kibana"

- name: "Flush handlers"
  meta: flush_handlers
