---
- name: "Start Kibana"
  systemd:
    name: kibana
    daemon_reload: yes
    enabled: yes
    state: started
  become: true

- name: "Restart Kibana"
  systemd:
    name: kibana
    daemon_reload: yes
    state: restarted
  become: true

- name: "Stop Kibana"
  systemd:
    name: kibana
    state: stopped
  become: true
